### ISSUE TITLE
Doesn't fix the NoClassDefFoundError: Ljava/util/Optional on Android

### ISSUE THREAD

**Issue by pasupulaphani** [stefan-zobel/streamsupport#5] opened 2018-11-13 11:50 UTC
A Java8 lib on Android uses java/util/Optional and it breaks on Android  API <24. I would like to know how can I fix it using this library.

**Comment by stefan-zobel** [comment] 2018-11-13 11:57
Can you change the code of that library to use java8.util.Optional? Otherwise ProGuard / DexGuard might be help. See https://github.com/stefan-zobel/streamsupport/issues/2#issuecomment-382084264

Regards,
Stefan

**Comment by netomi** [comment] 2018-11-15 11:03
ProGuard 6.1.0 beta 1 has been released with support to backport Java 8 stream & time API to older Android devices by using the streamsupport / threeten library.

Some more information can be found here: https://sourceforge.net/p/proguard/discussion/182455/thread/d06bac14c6/

**Comment by stefan-zobel** [comment] 2018-11-15 13:29
Hi Thomas, @netomi 

that's cool! However, I'm completely at loss how I'm supposed to make it work.
Could you give please an example how it must be configured?

I didn't find anything related to the backport option in the ProGuard manual at Guardsquare (or a manual that's specific to 6.1.0 beta1).
My initial attempts to backport uses of the Stream API simply ignored the presence of the streamsupport library.

Regards,
Stefan

**Comment by netomi** [comment] 2018-11-15 14:04
Hi,

thats really not well explained in the documentation. You can provide a -target option to control to which Java version the code shall be backported.

E.g. -target 1.7

Here an example output:

ProGuard, version 6.1.0 beta1
Reading input...
Reading program directory [/home/tn/workspace/guardsquare/releases/proguard6.1.0beta1/tmp/input]
Reading program jar [/home/tn/workspace/guardsquare/releases/proguard6.1.0beta1/tmp/streamsupport-1.6.3.jar]
Reading library jar [/home/tn/workspace/android/android-sdk/platforms/android-24/android.jar]
Initializing...
Ignoring unused library classes...
  Original number of library classes: 3823
  Final number of library classes:    426
Backporting class files...
  Number of converted string concatenations:     0
  Number of converted lambda expressions:        0
  Number of converted static interface methods:  0
  Number of converted default interface methods: 0
  Number of replaced Java 7+ method calls:       0
  Number of replaced Java 8 stream method calls: 142
  Number of replaced Java 8 time method calls:   0
Printing kept classes, fields, and methods...
Inlining subroutines...
Setting target versions...
Preverifying...
Writing output...
Preparing output jar [/home/tn/workspace/guardsquare/releases/proguard6.1.0beta1/tmp/protected.jar]
  Copying resources from program directory [/home/tn/workspace/guardsquare/releases/proguard6.1.0beta1/tmp/input]
  Copying resources from program jar [/home/tn/workspace/guardsquare/releases/proguard6.1.0beta1/tmp/streamsupport-1.6.3.jar]

**Comment by netomi** [comment] 2018-11-15 14:08
If you do not specify any -target option, no backporting will be performed. With 1.6 some additional Java 7 calls are backported to be compatible with Java 6.

**Comment by stefan-zobel** [comment] 2018-11-15 14:10
Thanks. The "-target" option is clear. I've tried that with 1.6 and added the streamsupport jar as a library jar (but obviously the test doesn't use any of the "java8.util" methods from the jar). I guess the "Number of replaced Java 8 stream method calls: 0" output proofs that the backporter gets called.

Perhaps I should have been more clear: I tried to use the GUI, but to noeffect.

Thanks,
Stefan

**Comment by stefan-zobel** [comment] 2018-11-15 14:15
This is the test code I want to be rewritten:

```
package test;

import java.util.stream.IntStream;

public final class Util {

   public static long getCount() {
      return IntStream.range(0, 11).sum();
   }
}

```

**Comment by netomi** [comment] 2018-11-15 14:21
Yes the problem is because you added the streamsupport library as libraryjar.
Try adding it as injar, then it should work.

Otherwise Proguard will remove all unneeded library classes (java8.** is not used yet) and then it can not backport anymore.

**Comment by netomi** [comment] 2018-11-15 14:23
If you want to include the streamsupport library as libraryjar, you have to apply a little trick to avoid the shrinking of library classes, add:

-useuniqueclassmembernames

**Comment by stefan-zobel** [comment] 2018-11-15 14:39
Ah yes, "-injar" makes sense. Now it works! Nice addition to my toolbox :+1: 

Thanks,
Stefan

**Comment by stefan-zobel** [comment] 2018-11-15 15:02
@pasupulaphani

If you still have that problem with your library, ProGuard 6.1.0 beta 1 might be worth giving a try.
streamsupport on its own won't magically rewrite any libraries you happen to use in your project.
Let me know if you have any follow-up questions.

Regards,
Stefan

**Closed by stefan-zobel** 2018-11-15 15:02 UTC
Labels: question

**Comment by stefan-zobel** [comment] 2018-11-15 19:55
Note: OP's original problem seems to be https://github.com/iotaledger/iota-java/issues/133
